"""Add User and Response models

Revision ID: c630db47885a
Revises: 
Create Date: 2024-02-24 14:04:21.256138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c630db47885a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('cancel_triggers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('time_before_send', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'FINISHED', name='userstatusenum'), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_response_id', sa.Integer(), nullable=True),
    sa.Column('last_response_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['next_response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('responses')
    # ### end Alembic commands ###
